# Generated by Django 5.0.6 on 2024-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydata',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
